name: cidl_mc_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - scipy
  - torchvision
  - ipykernel 
  - ipython
  - scikit-learn
  - pip
  - pip:
      - git+https://github.com/jlederer1/DKST.git@main